### ISSUE TITLE
AddToHueAndSaturation TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

### ISSUE THREAD

**Issue by gmonkman** [aleju/imgaug#131]
Getting the error in the title using AddToHueAndSaturation with statistical distributions for value. Was using iap.Normal which produced same error.

```
from imgaug import augmenters as iaa
from imgaug import parameters as iap

seq = iaa.Sequential([iaa.AddToHueAndSaturation(iap.Uniform(-30, 30), from_colorspace='BGR', per_channel=0.3)], random_order=False)
images_aug = seq.augment_image(img)

Traceback (most recent call last):
  File "<debug input>", line 1, in <module>
  File "C:\Python354x64\lib\site-packages\imgaug\augmenters\meta.py", line 257, in augment_image
    return self.augment_images([image], hooks=hooks)[0]
  File "C:\Python354x64\lib\site-packages\imgaug\augmenters\meta.py", line 365, in augment_images
    hooks=hooks
  File "C:\Python354x64\lib\site-packages\imgaug\augmenters\meta.py", line 1429, in _augment_images
    hooks=hooks
  File "C:\Python354x64\lib\site-packages\imgaug\augmenters\meta.py", line 365, in augment_images
    hooks=hooks
  File "C:\Python354x64\lib\site-packages\imgaug\augmenters\color.py", line 114, in _augment_images
    hooks=hooks,
  File "C:\Python354x64\lib\site-packages\imgaug\augmenters\meta.py", line 365, in augment_images
    hooks=hooks
  File "C:\Python354x64\lib\site-packages\imgaug\augmenters\meta.py", line 1429, in _augment_images
    hooks=hooks
  File "C:\Python354x64\lib\site-packages\imgaug\augmenters\meta.py", line 365, in augment_images
    hooks=hooks
  File "C:\Python354x64\lib\site-packages\imgaug\augmenters\meta.py", line 2052, in _augment_images
    hooks=hooks
  File "C:\Python354x64\lib\site-packages\imgaug\augmenters\meta.py", line 365, in augment_images
    hooks=hooks
  File "C:\Python354x64\lib\site-packages\imgaug\augmenters\meta.py", line 1429, in _augment_images
    hooks=hooks
  File "C:\Python354x64\lib\site-packages\imgaug\augmenters\meta.py", line 365, in augment_images
    hooks=hooks
  File "C:\Python354x64\lib\site-packages\imgaug\augmenters\arithmetic.py", line 140, in _augment_images
    image += sample
TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'
```

**Comment by aleju** [comment]
This is now fixed in master. For images it might still be "cleaner" to use `DiscreteUniform(a, b)` instead of `Uniform(a, b)` and `Discretize(Normal(loc, scale))` for normal distributions, though floats should now work too.
