### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 

### ISSUE THREAD

**Issue by tomjairus** [aleju/imgaug#233]
Collecting git+https://github.com/aleju/imgaug
  Cloning https://github.com/aleju/imgaug to c:\users\tomjai~1.por\appdata\local\temp\pip-req-build-9hgks9w2
Requirement already satisfied: scipy in c:\anaconda\envs\tfp36\lib\site-packages (from imgaug==0.2.7) (1.2.0)
Requirement already satisfied: scikit-image>=0.11.0 in c:\anaconda\envs\tfp36\lib\site-packages (from imgaug==0.2.7) (0.14.1)
Requirement already satisfied: numpy>=1.15.0 in c:\anaconda\envs\tfp36\lib\site-packages (from imgaug==0.2.7) (1.15.4)
Requirement already satisfied: six in c:\anaconda\envs\tfp36\lib\site-packages (from imgaug==0.2.7) (1.12.0)
Requirement already satisfied: imageio in c:\anaconda\envs\tfp36\lib\site-packages (from imgaug==0.2.7) (2.4.1)
Requirement already satisfied: Pillow in c:\anaconda\envs\tfp36\lib\site-packages (from imgaug==0.2.7) (5.4.1)
Requirement already satisfied: matplotlib in c:\anaconda\envs\tfp36\lib\site-packages (from imgaug==0.2.7) (3.0.2)
Collecting Shapely (from imgaug==0.2.7)
  Using cached https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\TOMJAI~1.POR\AppData\Local\Temp\pip-install-7mpmh4ku\Shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\TOMJAI~1.POR\AppData\Local\Temp\pip-install-7mpmh4ku\Shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "C:\anaconda\envs\tfp36\lib\ctypes\__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found

**Comment by aleju** [comment]
It looks like shapely for some reason cannot be installed on your system. You could try again installing it individually, e.g. directly from their repository. Maybe that works.
If that doesn't work, you can skip Shapely as it is very unlikely that you're going to need it anyways and I think that latest version of imgaug in the repo only imports Shapely if it actually needs it. So install the other dependencies manually, e.g. via `pip install six numpy scipy Pillow matplotlib scikit-image opencv-python imageio` and then try installing imgaug without the dependencies, e.g. via `pip install git+https://github.com/aleju/imgaug --no-deps`.

**Comment by tomjairus** [comment]
Thank you for the comment, I successfully install Shapely using the package in this site https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely

**Comment by pari0805** [comment]
@tomjairus can you please help me to install this package. I don't know how to install this. And I have downloaded the package from the site you mentioned.

**Comment by aleju** [comment]
You can skip shapely if you have problems with it. Most of `imgaug` should run without it.

**Comment by bharath5673** [comment]
> It looks like shapely for some reason cannot be installed on your system. You could try again installing it individually, e.g. directly from their repository. Maybe that works.
> If that doesn't work, you can skip Shapely as it is very unlikely that you're going to need it anyways and I think that latest version of imgaug in the repo only imports Shapely if it actually needs it. So install the other dependencies manually, e.g. via `pip install six numpy scipy Pillow matplotlib scikit-image opencv-python imageio` and then try installing imgaug without the dependencies, e.g. via `pip install git+https://github.com/aleju/imgaug --no-deps`.

superb. it worked.. 
#MRCNN

**Comment by rfernandezv** [comment]
> It looks like shapely for some reason cannot be installed on your system. You could try again installing it individually, e.g. directly from their repository. Maybe that works.
> If that doesn't work, you can skip Shapely as it is very unlikely that you're going to need it anyways and I think that latest version of imgaug in the repo only imports Shapely if it actually needs it. So install the other dependencies manually, e.g. via `pip install six numpy scipy Pillow matplotlib scikit-image opencv-python imageio` and then try installing imgaug without the dependencies, e.g. via `pip install git+https://github.com/aleju/imgaug --no-deps`.

it works, thanks.

**Comment by AkshatRepo** [comment]
The complete process to install shapely is described in this article which works perfectly fine and this article will clear your related error as well. The link of that article is
<a href="https://www.akshatvasistha.com/2019/10/how-do-real-time-image-segmentation-mask-rcnn.html"> Real-time image segmentation with MaskRCNN </a>
