### ISSUE TITLE
Rotation, which changes shape

### ISSUE THREAD

**Issue by RomanSteinberg** [aleju/imgaug#35]
As far as I can see your rotation is intended for square images. I am interested in using rotation like in the following code:
```
from scipy.ndimage.interpolation import rotate
# some code
new_image = rotate(image, angle, reshape=True)
```
Thus, it will transform image with shape (h,w) into image with shape (w,h) without any scaling by one of the  axies. Can I make it using your library in some way or should I make a pull request?

**Comment by aleju** [comment]
That's not part of the library currently. Your description sounds like you just want to have rotation by 90 degrees (shape (h,w) to (w,h))? Then you can just change `Fliplr` to use numpy's rot90 method, i.e. something like the following should work (but only with lists, not arrays):
```python
class Rot90(Augmenter):
    def __init__(self, p=0, name=None, deterministic=False, random_state=None):
        super(Rot90, self).__init__(name=name, deterministic=deterministic, random_state=random_state)

        if ia.is_single_number(p):
            self.p = Binomial(p)
        elif isinstance(p, StochasticParameter):
            self.p = p
        else:
            raise Exception("Expected p to be int or float or StochasticParameter, got %s." % (type(p),))

    def _augment_images(self, images, random_state, parents, hooks):
        assert isinstance(image, list)
        nb_images = len(images)
        samples = self.p.draw_samples((nb_images,), random_state=random_state)
        for i in sm.xrange(nb_images):
            if samples[i] == 1:
                images[i] = np.rot90(images[i], k=1)
        return images

    def _augment_keypoints(self, keypoints_on_images, random_state, parents, hooks):
        nb_images = len(keypoints_on_images)
        samples = self.p.draw_samples((nb_images,), random_state=random_state)
        for i, keypoints_on_image in enumerate(keypoints_on_images):
            if samples[i] == 1:
                width, height = keypoints_on_image.shape[0:2]
                for keypoint in keypoints_on_image.keypoints:
                    keypoint.x, keypoint.y = keypoint.y, keypoint.x
                keypoints_on_image.shape = (width, height)
        return keypoints_on_images

    def get_parameters(self):
        return [self.p]
```
then just use `aug = iaa.Rot90(0.5); images_aug = aug.augment_images([image1, image2])`.

**Comment by RomanSteinberg** [comment]
Will you include this code in the library?

**Comment by ahmedmazari-dhatim** [comment]
@aleju ,
when l run  :  
`aug = iaa.Rot90(0.5); images_aug = aug.augment_images([image1, image2])`

l get the following error 
```
Traceback (most recent call last):
  File "/home/ahmed/imgaug/test_simple.py", line 47, in <module>
    images_aug = seq.augment_images(image)
  File "/home/ahmed/imgaug/imgaug/augmenters.py", line 244, in augment_images
    hooks=hooks
  File "/home/ahmed/imgaug/imgaug/augmenters.py", line 4349, in _augment_images
    assert isinstance(image, list)
NameError: global name 'image' is not defined
```

**Comment by RomanSteinberg** [comment]
> l get the following error
It just a misspelling. It should be `images` variable for sure.

**Comment by ahmedmazari-dhatim** [comment]
@RomanSteinberg , where ?

**Comment by aleju** [comment]
@ahmedmazari-dhatim change `assert isinstance(image, list)` to `assert isinstance(images, list)` (after the line `def _augment_images(...)`).
@RomanSteinberg rot90 will probably be included in the library (when I find the time).

**Comment by RomanSteinberg** [comment]
@aleju your implementation of `_augment_keypoints` seems to be incorrect. Because you trying to flip keypoints along the main diagonal. This is not equivalent to the rotation. So, the following code is my implementation.
```
def _augment_keypoints(self, keypoints_on_images, random_state, parents, hooks):
        nb_images = len(keypoints_on_images)
        samples = self.p.draw_samples((nb_images,), random_state=random_state)
        for i, keypoints_on_image in enumerate(keypoints_on_images):
            if samples[i] == 1:
                width, height = keypoints_on_image.shape[0:2]
                for keypoint in keypoints_on_image.keypoints:
                    keypoint.x, keypoint.y = keypoint.y, width - keypoint.x
                keypoints_on_image.shape = (height, width)
        return keypoints_on_images
```

**Comment by ahmedmazari-dhatim** [comment]
Thanks a lot

**Comment by aleju** [comment]
not yet, its on the todo list

**Comment by DNXie** [comment]
@aleju 
Can the library let the users  select the angle they want for rotating, not for default 45 degree. What if I only want my image to rotate 90, 180, 270 degree, how can I implement it?

**Comment by DNXie** [comment]
@aleju  I think it helps! Thanks a lot!
