### ISSUE TITLE
numpy.dtype("f16") is not available (exception in dtype.py)

### ISSUE THREAD

**Issue by KUR-creative** [aleju/imgaug#358]
Hi,

```python
Traceback (most recent call last):
  File "D:\SEGMENT\new-bioseg\seg\lib\site-packages\imgaug\dtypes.py", line 65, in get_minimal_dtype
    promoted_dt_highres = np.dtype(promoted_dt_highres)
TypeError: data type "f16" not understood

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 383, in <module>
    main(experiment_yml_path)
  File "train.py", line 344, in main
    callbacks=[model_checkpoint,tboard,reduce_lr])
  File "D:\SEGMENT\new-bioseg\seg\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "D:\SEGMENT\new-bioseg\seg\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "D:\SEGMENT\new-bioseg\seg\lib\site-packages\keras\engine\training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "D:\SEGMENT\new-bioseg\seg\lib\site-packages\keras\utils\data_utils.py", line 709, in get
    six.reraise(*sys.exc_info())
  File "D:\SEGMENT\new-bioseg\seg\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "D:\SEGMENT\new-bioseg\seg\lib\site-packages\keras\utils\data_utils.py", line 685, in get
    inputs = self.queue.get(block=True).get()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 608, in get
    raise self._value
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "D:\SEGMENT\new-bioseg\seg\lib\site-packages\keras\utils\data_utils.py", line 626, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
  File "train.py", line 80, in batch_gen
    img_batch = img_aug.augment_images(img_batch.astype(np.float32))
  File "D:\SEGMENT\new-bioseg\seg\lib\site-packages\imgaug\augmenters\meta.py", line 603, in augment_images
    hooks=hooks
  File "D:\SEGMENT\new-bioseg\seg\lib\site-packages\imgaug\augmenters\meta.py", line 2823, in _augment_images
    hooks=hooks
  File "D:\SEGMENT\new-bioseg\seg\lib\site-packages\imgaug\augmenters\meta.py", line 515, in augment_images
    hooks=hooks
  File "D:\SEGMENT\new-bioseg\seg\lib\site-packages\imgaug\augmenters\arithmetic.py", line 354, in _augment_images
    increase_itemsize_factor=2)
  File "D:\SEGMENT\new-bioseg\seg\lib\site-packages\imgaug\dtypes.py", line 135, in promote_array_dtypes_
    dt = get_minimal_dtype(dtypes, increase_itemsize_factor=increase_itemsize_factor)
  File "D:\SEGMENT\new-bioseg\seg\lib\site-packages\imgaug\dtypes.py", line 77, in get_minimal_dtype
    increase_itemsize_factor
TypeError: Unable to create a numpy dtype matching the name 'f16'. This error was caused when trying to find a minimal dtype covering the dtypes 'float32, float64' (which was determined to be 'float64') and then increasing its resolution (aka itemsize) by a factor of 2. This error can be avoided by choosing arrays with lower resolution dtypes as inputs, e.g. by reducing float32 to float16.
```

Maybe numpy.dtype("f16") didn't works in numpy 1.10.
(https://docs.scipy.org/doc/numpy/user/basics.types.html)

So I edited imgaug/dtype.py line 65
(https://github.com/Blosc/bcolz/issues/270)

```python
def get_minimal_dtype(arrays, increase_itemsize_factor=1):
    input_dts = [array.dtype if not isinstance(array, np.dtype) else array
                 for array in arrays]
    promoted_dt = np.promote_types(*input_dts)
    if increase_itemsize_factor > 1:
        promoted_dt_highres = "%s%d" % (promoted_dt.kind, promoted_dt.itemsize * increase_itemsize_factor)
        try:
            #promoted_dt_highres = np.dtype(promoted_dt_highres)
            promoted_dt_highres = np.dtype(np.longdouble) # <---------------------------
            return promoted_dt_highres
        except TypeError:
            raise TypeError(
                ("Unable to create a numpy dtype matching the name '%s'. "
                 + "This error was caused when trying to find a minimal dtype covering the dtypes '%s' (which was "
                 + "determined to be '%s') and then increasing its resolution (aka itemsize) by a factor of %d. "
                 + "This error can be avoided by choosing arrays with lower resolution dtypes as inputs, e.g. by "
                 + "reducing float32 to float16.") % (
                    promoted_dt_highres,
                    ", ".join([input_dt.name for input_dt in input_dts]),
                    promoted_dt.name,
                    increase_itemsize_factor
                )
            )
    return promoted_dt
```
..And it works.

**Comment by aleju** [comment]
This should be fixed in master.
