### ISSUE TITLE
[MacOS] IOError when running generate_example_images.py

### ISSUE THREAD

**Issue by erickim555** [aleju/imgaug#40]
When I clone the repo, and run the `generate_example_images.py`, I get a runtime error:
`
$ cd ~/repos/imgaug
$ python generate_example_images.py
[draw_per_augmenter_images] Loading image...
[draw_per_augmenter_images] Initializing...
[draw_per_augmenter_images] Augmenting...
Traceback (most recent call last):
  File "generate_example_images.py", line 290, in <module>
    main()
  File "generate_example_images.py", line 18, in main
    draw_per_augmenter_images()
  File "generate_example_images.py", line 252, in draw_per_augmenter_images
    misc.imsave("examples.jpg", output_image.draw())
  File "generate_example_images.py", line 271, in draw
    rows_drawn = [self.draw_row(title, images, subtitles) for title, images, subtitles in self.rows]
  File "generate_example_images.py", line 277, in draw_row
    title_cell = ia.draw_text(title_cell, x=2, y=2, text=title, color=[0, 0, 0], size=12)
  File "/Users/erickim/repos/imgaug/imgaug/imgaug.py", line 129, in draw_text
    font = ImageFont.truetype("DejaVuSans.ttf", size)
  File "/usr/local/lib/python2.7/site-packages/PIL/ImageFont.py", line 238, in truetype
    return FreeTypeFont(font, size, index, encoding)
  File "/usr/local/lib/python2.7/site-packages/PIL/ImageFont.py", line 127, in __init__
    self.font = core.getfont(font, size, index, encoding)
IOError: cannot open resource
`

A quick fix is to modify `imgaug/imgaug.py:128` and give the absolute path of the `DejaVuSans.ttf` file that is included in the repo:

`
diff --git a/imgaug/imgaug.py b/imgaug/imgaug.py
index 7e94c82..b2b2485 100644
--- a/imgaug/imgaug.py
+++ b/imgaug/imgaug.py
@@ -9,6 +9,7 @@ import math
 from scipy import misc
 import multiprocessing
 import threading
+import os
 import sys
 import six
 import six.moves as sm
@@ -125,7 +126,8 @@ def draw_text(img, y, x, text, color=[0, 255, 0], size=25):

     shape = img.shape
     img = Image.fromarray(img)
-    font = ImageFont.truetype("DejaVuSans.ttf", size)
+    font = ImageFont.truetype(os.path.join(os.path.abspath(os.path.split(__file__)[0]), "DejaVuSans.ttf"), size)
+
     context = ImageDraw.Draw(img)
     context.text((x, y), text, fill=tuple(color), font=font)
     img_np = np.asarray(img)
`

Thoughts on this change?

**Comment by aleju** [comment]
Yeah that looks like it should better be an absolute path. Will fix it in the library soon.
