### ISSUE TITLE
error thrown when calling   _draw_samples_image     ia.do_assert(regain_bottom <= crop_bottom)

### ISSUE THREAD

**Issue by cpoptic** [aleju/imgaug#445]
I'm trying to train a Mask RCNN model using imgaug for augmentations.  All of my images are 512x512 and I've updated the default config params from to:
    IMAGE_MAX_DIM = 512
    IMAGE_MIN_DIM = 512
    IMAGE_RESIZE_MODE = "none"  (I've also tried setting this to "square")

I keep encountering this error and have grown frustrated over several hours of troubleshooting.  From the 2nd to last error line, I'm guessing from the assert error that it has something to do with the   `regain_bottom <= crop_bottom` but I can't figure out where this condition is being violated.

Matterport's config.py file says (lines 98-101):

`    # If enabled, resizes instance masks to a smaller size to reduce
    # memory load. Recommended when using high-resolution images.
    USE_MINI_MASK = True
    MINI_MASK_SHAPE = (56, 56)  # (height, width) of the mini-mask`

But I think the mask_shape is sufficiently large enough to work on 512x512 images.

Here's the error:

> ERROR:root:Error processing image {'id': '2017050507084918155YBL-XR1IO000017.jpg', 'source': 'dental', 'path': 'D:\\PDS projects\\C137\\082819masks\\annotation_images\\2017050507084918155YBL-XR1IO000017.jpg', 'width': 512, 'height': 512, 'polygons': [{'all_points_x': [307, 321, 326, 319, 314, 305], 'all_points_y': [372, 347, 321, 305, 303, 334], 'name': 'polygon'}], 'r_object_name': ['decay']}
> 
> Traceback (most recent call last):
>   File "< my anaconda env >lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 1720, in data_generator
>     use_mini_mask=config.USE_MINI_MASK)
>   File "< my anaconda env >lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 1264, in load_image_gt
>     hooks=imgaug.HooksImages(activator=hook))
>   File "< my anaconda env >lib\site-packages\imgaug\augmenters\meta.py", line 323, in augment_image
>     return self.augment_images([image], hooks=hooks)[0]
>   File "< my anaconda env >lib\site-packages\imgaug\augmenters\meta.py", line 431, in augment_images
>     hooks=hooks
>   File "< my anaconda env >lib\site-packages\imgaug\augmenters\meta.py", line 1514, in _augment_images
>     hooks=hooks
>   File "< my anaconda env >lib\site-packages\imgaug\augmenters\meta.py", line 431, in augment_images
>     hooks=hooks
>   File "< my anaconda env >lib\site-packages\imgaug\augmenters\size.py", line 611, in _augment_images
>     crop_top, crop_right, crop_bottom, crop_left, pad_top, pad_right, pad_bottom, pad_left, pad_mode, pad_cval = self._draw_samples_image(seed, height, width)
>   File "< my anaconda env >lib\site-packages\imgaug\augmenters\size.py", line 727, in _draw_samples_image
>     ia.do_assert(regain_bottom <= crop_bottom)
>   File "< my anaconda env >lib\site-packages\imgaug\imgaug.py", line 678, in do_assert
>     raise AssertionError(str(message))
> AssertionError: Assertion failed.

`

Any help would be appreciated.  Please let me know if I'm doing something wrong with imgaug or rather if the problem lies with the Mask_RCNN configuration.  Thank you

**Comment by aleju** [comment]
I think this error could be thrown if the height and/or width of the input image/mask was `0`. Can you try installing version 0.3.0 of imgaug? In that version the crop mechanism was partially rewritten and the assert statement is now gone. The error messages should also be more descriptive now.

**Comment by cpoptic** [comment]
Thanks Alex.  I installed version  0.3.0 of imgaug, but still happening.
What else should I try?

**Comment by aleju** [comment]
Which error are you getting now exactly? The mentioned assert statement was removed, so it should be a different one. If it is still the same, my guess would be that it only looked like the library was updated and in reality the older version is still used for some reason.
