### ISSUE TITLE
Python3 installation failed

### ISSUE THREAD

**Issue by karolmajek** [aleju/imgaug#45]
I am using python3 without conda/env.

After running: 
`sudo pip3 install git+https://github.com/aleju/imgaug`
I receive:
```
Collecting git+https://github.com/aleju/imgaug
  Cloning https://github.com/aleju/imgaug to /tmp/pip-mn453yqe-build
*** Error in `/usr/bin/python3': free(): invalid pointer: 0x0000000001af2990 ***
======= Backtrace: =========
...
======= Memory map: ========
...
Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/imgaug.egg-info
    writing top-level names to pip-egg-info/imgaug.egg-info/top_level.txt
    writing requirements to pip-egg-info/imgaug.egg-info/requires.txt
    writing pip-egg-info/imgaug.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/imgaug.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/imgaug.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/imgaug.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/imgaug.egg-info/SOURCES.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code -6 in /tmp/pip-mn453yqe-build/
```

I am using manually build OpenCV 3.1.0-dev (from pyimagesearch tutorial)

**Comment by aleju** [comment]
Can you quickly try if it works without `sudo`? Sometimes that can cause problems.
Not entirely sure if the library works with OpenCV 3, but at least it shouldn't fail during installation.

**Comment by karolmajek** [comment]
Without `sudo` it tries to use cv2 from python2.7 from ROS

```
pip3 install git+https://github.com/aleju/imgaug
```

```
Collecting git+https://github.com/aleju/imgaug
  Cloning https://github.com/aleju/imgaug to /tmp/pip-pk4wk75e-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-pk4wk75e-build/setup.py", line 4, in <module>
        import cv2
    ImportError: /opt/ros/kinetic/lib/python2.7/dist-packages/cv2.so: undefined symbol: PyCObject_Type
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-pk4wk75e-build/setup.py", line 6, in <module>
        raise Exception("Could not find package 'cv2' (OpenCV). It cannot be automatically installed, so you will have to manually install it.")
    Exception: Could not find package 'cv2' (OpenCV). It cannot be automatically installed, so you will have to manually install it.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-pk4wk75e-build/
```

**Comment by aleju** [comment]
Hm not sure I can help you there. I just installed OpenCV 3.2 via the pyimagesearch tutorial in python3 and imgaug installed fine for me and seems to run without errors.
The install error without `sudo` also looks odd to me. If you run pip for python3, it should not look in python2.7/ for OpenCV.

**Comment by karolmajek** [comment]
Agree. I will try it on another machine.
Thanks!

**Comment by kaisark** [comment]
worked without sudo (ubuntu 16 - opencv 3.3 - python vitual env -  aws ec2 instance).

--------------
(dl4cv) ubuntu@ip-172-31-0-76:~$ pip3 install git+https://github.com/aleju/imgaug
Collecting git+https://github.com/aleju/imgaug
  Cloning https://github.com/aleju/imgaug to /tmp/pip-6ww78_6y-build
Requirement already satisfied: scipy in ./.virtualenvs/dl4cv/lib/python3.5/site-packages (from imgaug==0.2.5)
Requirement already satisfied: scikit-image>=0.11.0 in ./.virtualenvs/dl4cv/lib/python3.5/site-packages (from imgaug==0.2.5)
Requirement already satisfied: numpy>=1.7.0 in ./.virtualenvs/dl4cv/lib/python3.5/site-packages (from imgaug==0.2.5)
Requirement already satisfied: six in ./.virtualenvs/dl4cv/lib/python3.5/site-packages (from imgaug==0.2.5)
Requirement already satisfied: PyWavelets>=0.4.0 in ./.virtualenvs/dl4cv/lib/python3.5/site-packages (from scikit-image>=0.11.0->imgaug==0.2.5)
Requirement already satisfied: pillow>=2.1.0 in ./.virtualenvs/dl4cv/lib/python3.5/site-packages (from scikit-image>=0.11.0->imgaug==0.2.5)
Requirement already satisfied: matplotlib>=1.3.1 in ./.virtualenvs/dl4cv/lib/python3.5/site-packages (from scikit-image>=0.11.0->imgaug==0.2.5)
Requirement already satisfied: networkx>=1.8 in ./.virtualenvs/dl4cv/lib/python3.5/site-packages (from scikit-image>=0.11.0->imgaug==0.2.5)
Requirement already satisfied: cycler>=0.10 in ./.virtualenvs/dl4cv/lib/python3.5/site-packages (from matplotlib>=1.3.1->scikit-image>=0.11.0->imgaug==0.2.5)
Requirement already satisfied: python-dateutil>=2.1 in ./.virtualenvs/dl4cv/lib/python3.5/site-packages (from matplotlib>=1.3.1->scikit-image>=0.11.0->imgaug==0.2.5)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./.virtualenvs/dl4cv/lib/python3.5/site-packages (from matplotlib>=1.3.1->scikit-image>=0.11.0->imgaug==0.2.5)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.virtualenvs/dl4cv/lib/python3.5/site-packages (from matplotlib>=1.3.1->scikit-image>=0.11.0->imgaug==0.2.5)
Requirement already satisfied: pytz in ./.virtualenvs/dl4cv/lib/python3.5/site-packages (from matplotlib>=1.3.1->scikit-image>=0.11.0->imgaug==0.2.5)
Requirement already satisfied: decorator>=4.1.0 in ./.virtualenvs/dl4cv/lib/python3.5/site-packages (from networkx>=1.8->scikit-image>=0.11.0->imgaug==0.2.5)
Requirement already satisfied: setuptools in ./.virtualenvs/dl4cv/lib/python3.5/site-packages (from kiwisolver>=1.0.1->matplotlib>=1.3.1->scikit-image>=0.11.0->imgaug==0.2.5)
Installing collected packages: imgaug
  Running setup.py install for imgaug ... done
Successfully installed imgaug-0.2.5
