### ISSUE TITLE
AttributeError: 'RNG' object has no attribute 'randint'

### ISSUE THREAD

**Issue by KUR-creative** [aleju/imgaug#485]
When updated v0.3.0, It crashes.

```python
Traceback (most recent call last):
  File "train.py", line 403, in <module>
    main(experiment_yml_path) 
  File "train.py", line 364, in main
    callbacks=[model_checkpoint,tboard,reduce_lr])
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1297, in fit_generator
    steps_name='steps_per_epoch')
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 221, in model_iteration
    batch_data = _get_next_batch(generator)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 363, in _get_next_batch
    generator_output = next(generator)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/data_utils.py", line 918, in get
    six.reraise(*sys.exc_info())
  File "/home/deep-dos/.local/lib/python3.7/site-packages/six.py", line 696, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/data_utils.py", line 894, in get
    inputs = self.queue.get(block=True).get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/data_utils.py", line 828, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
  File "train.py", line 74, in batch_gen
    img_batch = aug_det.augment_images(img_batch)
  File "/home/deep-dos/.local/lib/python3.7/site-packages/imgaug/augmenters/meta.py", line 695, in augment_images
    hooks=hooks
  File "/home/deep-dos/.local/lib/python3.7/site-packages/imgaug/augmenters/meta.py", line 2961, in _augment_images
    images, random_state, parents, hooks, "augment_images")
  File "/home/deep-dos/.local/lib/python3.7/site-packages/imgaug/augmenters/meta.py", line 2995, in _augment_augmentables
    hooks=hooks
  File "/home/deep-dos/.local/lib/python3.7/site-packages/imgaug/augmenters/meta.py", line 633, in augment_images
    hooks=hooks
  File "/home/deep-dos/.local/lib/python3.7/site-packages/imgaug/augmenters/meta.py", line 4093, in _augment_images
    return self.func_images(images, random_state, parents, hooks)
  File "train.py", line 40, in func_images
    y = random_state.randint(0, h - size)
AttributeError: 'RNG' object has no attribute 'randint'
```

I fixed it by downgrading imgaug to v0.2.9

Thanks.

**Comment by aleju** [comment]
I guess you used an older example script that made use of `Lambda`?
Anyways, these old numpy random number sampling methods are now added to `RNG`. It should work again in master.

**Comment by KUR-creative** [comment]
Thank you for the quick fix!
