### ISSUE TITLE
 augment_batches(..., background=True) relaunches the same script it has been called upon.

### ISSUE THREAD

**Issue by Attrezzi** [aleju/imgaug#497]
Hello, 
I've been using imgaug these days and due to the amount of augmentations I need to perform, I decided to give a shot and use the multicore version of the augmentation.
In my script, I'm looping over the images contained in a folder. Once an image has been loaded, I copy it 100 times and fit these copies inside some UnnormalizedBatches. Then, I simply call  augment_batches(..., background=True) as provided in the notebook, but something strange happens. It seems that each generated thread launches itself the script in which I call augment_batches.

The error shows in the console is:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Gabri\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Gabri\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\Gabri\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Gabri\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\Gabri\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Gabri\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Gabri\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Gabri\Desktop\Thesis\UICThesis\DataPreprocessing\data_augmentation.py", line 147, in <module>
    create_augmented_dataset()
  File "C:\Users\Gabri\Desktop\Thesis\UICThesis\DataPreprocessing\data_augmentation.py", line 123, in create_augmented_dataset
    for augmented_batch in augmentations.augment_batches(batches, background=True):
  File "C:\Users\Gabri\AppData\Local\Programs\Python\Python36\lib\site-packages\imgaug\augmenters\meta.py", line 473, in augment_batches
    with multicore.Pool(self) as pool:
  File "C:\Users\Gabri\AppData\Local\Programs\Python\Python36\lib\site-packages\imgaug\multicore.py", line 337, in __enter__
    _ = self.pool  # initialize internal multiprocessing pool instance
  File "C:\Users\Gabri\AppData\Local\Programs\Python\Python36\lib\site-packages\imgaug\multicore.py", line 152, in pool
    maxtasksperchild=self.maxtasksperchild)
  File "C:\Users\Gabri\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\Gabri\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
  File "C:\Users\Gabri\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()
  File "C:\Users\Gabri\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Gabri\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Gabri\AppData\Local\Programs\Python\Python36\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Gabri\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Gabri\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

Does someone have some hints on why this problem appears and how to solve it?

Thanks a lot!

**Comment by Attrezzi** [comment]
Okay, I've just solved now. As explained in this link [https://stackoverflow.com/questions/44560397/python-multiprocessing-iterates-over-script](url), the multiprocessing.pool on windows relaunches the whole script for each thread that has been spawned.
Lazily I've been launching the function containing the batch augmentation without the if __name__ == '__main__' condition. Once I've added it, everything works flawlessly.
