### ISSUE TITLE
sporadic segfault while augmenting, makes imgaug unusable

### ISSUE THREAD

**Issue by InnovArul** [aleju/imgaug#544]
I am facing sporadic segmentation faults while augmenting the images (images alone or with segmentation maps).
I have a simple augmentation script here: https://gist.github.com/InnovArul/9923bb2b19f98f251998d8d74d3c171b

```
OS: Ubuntu 16.04.3
imgaug version: 0.3.0
```

When the script is executed, sometimes it runs full 100 augmentations. But other times, it gives out a segmentation fault.

When I backtraced it in GDB, I got:
```
Thread 26 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff737fe700 (LWP 34404)]
__GI___libc_free (mem=0x4015) at malloc.c:2951
2951 malloc.c: No such file or directory.
(gdb) backtrace
#0 __GI___libc_free (mem=0x4015) at malloc.c:2951
#1 0x00007fffe6d29a39 in ?? () from /home/arul/miniconda3/envs/vos/lib/python3.7/site-packages/cv2/cv2.cpython-37m-x86_64-linux-gnu.so
#2 0x00007fffe69a0ef5 in ?? () from /home/arul/miniconda3/envs/vos/lib/python3.7/site-packages/cv2/cv2.cpython-37m-x86_64-linux-gnu.so
#3 0x00007fffe70a16c5 in ?? () from /home/arul/miniconda3/envs/vos/lib/python3.7/site-packages/cv2/cv2.cpython-37m-x86_64-linux-gnu.so
#4 0x00007fffe6de97e9 in ?? () from /home/arul/miniconda3/envs/vos/lib/python3.7/site-packages/cv2/cv2.cpython-37m-x86_64-linux-gnu.so
#5 0x00007fffe70a6c31 in ?? () from /home/arul/miniconda3/envs/vos/lib/python3.7/site-packages/cv2/cv2.cpython-37m-x86_64-linux-gnu.so
#6 0x00007fffe70aa5a7 in ?? () from /home/arul/miniconda3/envs/vos/lib/python3.7/site-packages/cv2/cv2.cpython-37m-x86_64-linux-gnu.so
#7 0x00007fffe6de963e in ?? () from /home/arul/miniconda3/envs/vos/lib/python3.7/site-packages/cv2/cv2.cpython-37m-x86_64-linux-gnu.so
#8 0x00007fffe6dea04a in ?? () from /home/arul/miniconda3/envs/vos/lib/python3.7/site-packages/cv2/cv2.cpython-37m-x86_64-linux-gnu.so
#9 0x00007fffe6dead1d in ?? () from /home/arul/miniconda3/envs/vos/lib/python3.7/site-packages/cv2/cv2.cpython-37m-x86_64-linux-gnu.so
#10 0x00007fffe6deae89 in ?? () from /home/arul/miniconda3/envs/vos/lib/python3.7/site-packages/cv2/cv2.cpython-37m-x86_64-linux-gnu.so
#11 0x00007ffff7bc16ba in start_thread (arg=0x7fff737fe700) at pthread_create.c:333
#12 0x00007ffff78f741d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

Any idea on what could be wrong?

**Comment by InnovArul** [comment]
The same script seem to work in windows 10. Puzzling!

**Comment by InnovArul** [comment]
I have re-created conda environment, installed imgaug from conda-forge channel, opencv3 from menpo channel. Now the segmentation fault is not occuring. I am not sure what solved the issue.
