### ISSUE TITLE
break pytorch's dataloader when num_workers > 0

### ISSUE THREAD

**Issue by xiadingZ** [aleju/imgaug#668]
I use imgaug in pytorch's dataset, but it can't work when dataloader's num_workers > 0. This is my code:

```
class ImgAugTransform:
    def __init__(self):
        self.aug = iaa.Sequential([
            iaa.Resize({"height":224, "width":224}),
            iaa.GammaContrast(1.5),
            iaa.Affine(rotate=(-25, 25)),
            iaa.Fliplr(0.3)
        ])

    def __call__(self, img, boxes):

        boxes = [BoundingBox(x1=box[0], y1=box[1], x2=box[2], y2=box[3]) for box in boxes]
        boxes = BoundingBoxesOnImage(boxes, shape=img.shape)
        return self.aug(image=img, bounding_boxes=boxes)
```
I try to instantiation this transform in `Dataset`'s `__init__`, or `__getitem__` method, but all not work. 

this is error message:
```
Traceback (most recent call last):
  File "main.py", line 110, in <module>
    main(hparams)
  File "main.py", line 45, in main
    trainer.fit(model)
  File "/Users/xd/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 887, in fit
    self.run_pretrain_routine(model)
  File "/Users/xd/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1001, in run_pretrain_routine
    False)
  File "/Users/xd/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 256, in _evaluate
    for batch_idx, batch in enumerate(dataloader):
  File "/Users/xd/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/Users/xd/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "/Users/xd/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 808, in _get_data
    success, data = self._try_get_data()
  File "/Users/xd/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 774, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 42297) exited unexpectedly
```

when I set dataloader's num_workers=0, it works well. but it will slow down my program. How can i do?

**Comment by aleju** [comment]
Hard to tell what the problem is, as the error just says that there was some error and nothing else. Try setting `cv2.setNumThreads(0)` within each child process. Sometimes that causes issues, particularly on Mac, which you seem to use.

Btw, take care of setting the seed in each child process. Otherwise you will get the same transformations, merely applied to different batches of data.

**Comment by VladKatsman** [comment]
i have the same issue

** Traceback (most recent call last):
  File "/home/katsman_vlad/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
  File "/home/katsman_vlad/.local/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 26645) is killed by signal: Segmentation fault. **
