### ISSUE TITLE
ValueError in augmenter 'UnnamedAllChannelsHistogramEqualization' 

### ISSUE THREAD

**Issue by NoamRosenberg** [aleju/imgaug#722]
Hi, so I basically use this function like all the others

``     aug = iaa.AllChannelsHistogramEqualization()
        img_aug, bbs_aug = aug(image=img, bounding_boxes=bbs)
``
The input image is a numpy array of dtype float32 and bbs is the boundingbox object supported by the library.

Then I get:

ValueError: Got dtype 'float32' in augmenter 'UnnamedAllChannelsHistogramEqualization' (class 'AllChannelsHistogramEqualization'), which is a forbidden dtype (bool, uint16, uint32, uint64, uint128, uint256, int8, int16, int32, int64, int128, int256, float16, float32, float64, float96, float128, float256).

**Comment by jspaezp** [comment]
Hello there!

I was able to reproduce the error and by looking at the documentation it would seem like the function supports only unsigned 8 bit ints `unit8` 

link to the api documentation:
https://imgaug.readthedocs.io/en/latest/source/api_augmenters_contrast.html#imgaug.augmenters.contrast.AllChannelsHistogramEqualization 

Additional chunk to reproduce the error

```python

import numpy as np
import imgaug as ia
import imgaug.augmenters as iaa
import cv2

ia.seed(1)

img = ia.quokka(size=(64, 64))

bbs = [ia.augmentables.bbs.BoundingBox(x1=10, y1=20, x2=20, y2=30),
       ia.augmentables.bbs.BoundingBox(x1=25, y1=50, x2=30, y2=60)]
bbs_oi = ia.augmentables.bbs.BoundingBoxesOnImage(bbs, shape=image.shape)

aug = iaa.AllChannelsHistogramEqualization()

img_aug, bbs_aug = aug(image=img, bounding_boxes=bbs)
# Works

img_aug, bbs_aug = aug(image=img.astype(np.float32), bounding_boxes=bbs)
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "/home/jspaezp/.local/lib/python3.8/site-packages/imgaug/augmenters/meta.py", line 2027, in __call__
#     return self.augment(*args, **kwargs)
#   File "/home/jspaezp/.local/lib/python3.8/site-packages/imgaug/augmenters/meta.py", line 1998, in augment
#     batch_aug = self.augment_batch_(batch, hooks=hooks)
#   File "/home/jspaezp/.local/lib/python3.8/site-packages/imgaug/augmenters/meta.py", line 643, in augment_batch_
#     batch_inaug = self._augment_batch_(
#   File "/home/jspaezp/.local/lib/python3.8/site-packages/imgaug/augmenters/contrast.py", line 1386, in _augment_batch_
#     iadt.allow_only_uint8(images, augmenter=self)
#   File "/home/jspaezp/.local/lib/python3.8/site-packages/imgaug/dtypes.py", line 535, in allow_only_uint8
#     return gate_dtypes_strs(
#   File "/home/jspaezp/.local/lib/python3.8/site-packages/imgaug/dtypes.py", line 349, in gate_dtypes_strs
#     return _gate_dtypes(dtypes, allowed, disallowed, augmenter=augmenter)
#   File "/home/jspaezp/.local/lib/python3.8/site-packages/imgaug/dtypes.py", line 476, in _gate_dtypes
#     raise ValueError(
# ValueError: Got dtype 'float32' in augmenter 'UnnamedAllChannelsHistogramEqualization' (class 'AllChannelsHistogramEqualization'), which is a forbidden dtype (bool, int8, uint64, int16, float16, uint16, float32, uint32, int32, int64, float64, float128).
```

As a workaround you could try scaling your images to the 0-255 range from what you have and convert them temporarly to unit8. Then, after the augmentation convert back to floats, this would loose some precision but ... might be good enough for your purpose.

If not I think you might need to implement your own augmenter to deal with the ranges you are using.

This function seems to be a reasonable starting point for your purposes:
https://gist.github.com/TimSC/6f429dfacf523f5c9a58c3b629f0540e

Best,
Sebastian
