### ISSUE TITLE
AttributeError: module 'imgaug' has no attribute 'deepcopy'

### ISSUE THREAD

**Issue by WorstCodeWay** [aleju/imgaug#785]
Hi, I meet a problem when augmenting my dataset. My codes as following:
```
  annos = imgs_anns["shapes"]
  for anno in annos:
        polygon = []
        points = anno["points"]
        px = [point[0] for point in points]
        py = [point[1] for point in points]
        poly = [(x + 0.5, y + 0.5) for x, y in zip(px, py)]
        ia.Polygon(poly)
        polygon.append(ia)
        polygons = ia.PolygonsOnImage(polygon, shape=image.shape)
   images_aug, polygons_aug = seq(images=[image], polygons=polygons)
```
But the last line gives the error
```
Traceback (most recent call last):
  File "tools/augmentation.py", line 58, in <module>
    augment_images("../pandents(colored)/dataset/train")
  File "tools/augmentation.py", line 51, in augment_images
    images_aug, polygons_aug = seq(images=[image], polygons=polygons)
  File "/home/jason/Documents/vist/deeplearning/venv/lib/python3.6/site-packages/imgaug/augmenters/meta.py", line 2027, in __call__
    return self.augment(*args, **kwargs)
  File "/home/jason/Documents/vist/deeplearning/venv/lib/python3.6/site-packages/imgaug/augmenters/meta.py", line 1998, in augment
    batch_aug = self.augment_batch_(batch, hooks=hooks)
  File "/home/jason/Documents/vist/deeplearning/venv/lib/python3.6/site-packages/imgaug/augmenters/meta.py", line 597, in augment_batch_
    batch_inaug = batch_norm.to_batch_in_augmentation()
  File "/home/jason/Documents/vist/deeplearning/venv/lib/python3.6/site-packages/imgaug/augmentables/batches.py", line 456, in to_batch_in_augmentation
    polygons=_copy(self.polygons_unaug),
  File "/home/jason/Documents/vist/deeplearning/venv/lib/python3.6/site-packages/imgaug/augmentables/batches.py", line 447, in _copy
    return utils.copy_augmentables(var)
  File "/home/jason/Documents/vist/deeplearning/venv/lib/python3.6/site-packages/imgaug/augmentables/utils.py", line 19, in copy_augmentables
    result.append(augmentable.deepcopy())
  File "/home/jason/Documents/vist/deeplearning/venv/lib/python3.6/site-packages/imgaug/augmentables/polys.py", line 2107, in deepcopy
    polygons = [poly.deepcopy() for poly in self.polygons]
  File "/home/jason/Documents/vist/deeplearning/venv/lib/python3.6/site-packages/imgaug/augmentables/polys.py", line 2107, in <listcomp>
    polygons = [poly.deepcopy() for poly in self.polygons]
AttributeError: module 'imgaug' has no attribute 'deepcopy'

```
What's wrong? I tried: reinstall imgaug as following, but no luck
```
pip3 uninstall imgaug && pip3 install git+https://github.com/aleju/imgaug.git
```

**Comment by WorstCodeWay** [comment]
Sorry, I find a coding error in `polygon.append(ia)`
